export enum ROUTES {
  HOME = "/",
  AUTH = "/auth",
  LOGIN = "sign-in",
  REGISTER = "sign-up",
  PROJECTS = "projects",
  CLIENTS = "clients",
  NOTES = "notes",
  TASKS = "tasks",
  USER = "users",
  SETTINGS = "settings",
  NOTIFICATIONS = "notifications",
  PLANS = "plans",
  NO_ACCESS = "no-access",
}
