name: Deploy Frontend
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update code
        run: |
          ls -la /home/mezabizon/projects/time_tracker/frontend/Dockerfile
          ls -la /home/mezabizon/projects/time_tracker/docker-compose.yml
          cd /home/mezabizon/projects/time_tracker/frontend/
          git pull origin main
          cd ..
          docker-compose build frontend
          docker-compose up -d frontend

